# Generated by Django 4.2.7 on 2023-12-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('Event_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('E_name', models.CharField(max_length=255)),
                ('Org_username', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Venue Name')),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('post_code', models.CharField(max_length=12, verbose_name='Postal Code')),
                ('phone', models.CharField(max_length=25, verbose_name='Phone Number')),
                ('web', models.URLField(verbose_name='Website Address')),
                ('email', models.EmailField(max_length=254, verbose_name='Venue Email')),
            ],
            options={
                'db_table': 'Venue',
                'managed': False,
            },
        ),
    ]
