# Generated by Django 4.2.7 on 2023-12-11 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_affiliated_attends_authgroup_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrangesguests',
            name='guest',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
        migrations.DeleteModel(
            name='ArrangesGuests',
        ),
    ]
