# Generated by Django 4.2.7 on 2023-12-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_arrangesguests_guest_delete_venue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('u_username', models.CharField(db_column='U_username', max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Saved',
                'managed': False,
            },
        ),
    ]
